# I. Models
## 1. Undersamlping 
- Random undersampling : EasyEnsembleClassifier using adaboost classifier
- Random undersampling : EasyEnsembleClassifier using gradientboosting classifier



In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#import Data
df = pd.read_csv('../../Data/cleaned_data_one_hot.csv')

# drop BatchId
df = df.drop(['BatchId'], axis=1)
df.head()

AccountId  SubscriptionId  CustomerId  ProductId  Value  PricingStrategy  \
0       3957             887        4406         10   1000                2   
1       4841            3829        4406          6     20                2   
2       4229             222        4683          1    500                2   
3        648            2185         988         21  21800                2   
4       4841            3829         988          6    644                2   

   ProductCategory_airtime  ProductCategory_data_bundles  \
0                        1                             0   
1                        0                             0   
2                        1                             0   
3                        0                             0   
4                        0                             0   

   ProductCategory_financial_services  ProductCategory_movies  ...  \
0                                   0                       0  ...   
1                                   1                       0  ...   
2                                   0                       0  ...   
3                                   0                       0  ...   
4                                   1                       0  ...   

   ProviderId_2  ProviderId_3  ProviderId_4  ProviderId_5  ProviderId_6  \
0             0             0             0             0             1   
1             0             0             1             0             0   
2             0             0             0             0             1   
3             0             0             0             0             0   
4             0             0             1             0             0   

   Hour_1  Hour_2  Hour_3  Hour_4  Fraud  
0       0       0       0       1      0  
1       0       0       0       1      0  
2       0       0       0       1      0  
3       0       0       0       1      0  
4       0       0       0       1      0  

[5 rows x 30 columns]

In [3]:
# split data into train and test
from sklearn.model_selection import train_test_split
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# find the number of fraud and non-fraud cases in the training data
print('Number of fraud and not fraud cases in training data: \n', y_train.value_counts())
print('Number of fraud and not fraud cases in test data: \n', y_test.value_counts())



Number of fraud and not fraud cases in training data: 
 0    76372
1      157
Name: Fraud, dtype: int64
Number of fraud and not fraud cases in test data: 
 0    19097
1       36
Name: Fraud, dtype: int64


In [5]:
## import EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import classification_report, confusion_matrix, f1_score

# create model
eec = EasyEnsembleClassifier(n_estimators=20, estimator=AdaBoostClassifier() , random_state=42, n_jobs=-1, verbose=0)
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[18888   209]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     19097
           1       0.15      1.00      0.26        36

    accuracy                           0.99     19133
   macro avg       0.57      0.99      0.63     19133
weighted avg       1.00      0.99      0.99     19133



In [6]:
from sklearn.ensemble import GradientBoostingClassifier
# create model
eec = EasyEnsembleClassifier(n_estimators=50, estimator=GradientBoostingClassifier() , random_state=42, n_jobs=-1, verbose=0 )
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[18810   287]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     19097
           1       0.11      1.00      0.20        36

    accuracy                           0.98     19133
   macro avg       0.56      0.99      0.60     19133
weighted avg       1.00      0.98      0.99     19133



In [23]:
from sklearn.ensemble import GradientBoostingClassifier
# create model
eec = EasyEnsembleClassifier(n_estimators=40, estimator=GradientBoostingClassifier(), sampling_strategy=0.25 , random_state=42, n_jobs=-1, verbose=0 )
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19009    88]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.29      1.00      0.45        36

    accuracy                           1.00     19133
   macro avg       0.65      1.00      0.72     19133
weighted avg       1.00      1.00      1.00     19133



In [8]:
# create model
eec = EasyEnsembleClassifier(n_estimators=20, estimator=AdaBoostClassifier(), sampling_strategy=0.25 , random_state=42, n_jobs=-1, verbose=0)
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19030    67]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.35      1.00      0.52        36

    accuracy                           1.00     19133
   macro avg       0.67      1.00      0.76     19133
weighted avg       1.00      1.00      1.00     19133



## 2. Undersampling and Oversampling
- SMOTEENN : SMOTENC (Categorical and numerical features)+ ENN

In [9]:
X_train.shape

(76529, 29)

In [10]:
#import SMOTENC 
from imblearn.over_sampling import SMOTENC
#import ENN
from imblearn.under_sampling import EditedNearestNeighbours

#import SMOTEENN
from imblearn.combine import SMOTEENN

# create model of over and under sampling : SMOTENC and ENN
# categorical features : 'AccountId','SubscriptionId','CustomerId', 'ProductId','PricingStrategy','ProductCategory_airtime','ProductCategory_data_bundles','ProductCategory_financial_services','ProductCategory_movies','ProductCategory_other','ProductCategory_ticket','ProductCategory_transport','ProductCategory_tv','ProductCategory_utility_bill','ChannelId_1','ChannelId_2','ChannelId_3','ChannelId_5','ProviderId_1','ProviderId_2','ProviderId_3','ProviderId_4','ProviderId_5','ProviderId_6','Hour_1','Hour_2','Hour_3','Hour_4'
#smotenc= SMOTENC(categorical_features=['AccountId','SubscriptionId','CustomerId', 'ProductId','PricingStrategy','ProductCategory_airtime','ProductCategory_data_bundles','ProductCategory_financial_services','ProductCategory_movies','ProductCategory_other','ProductCategory_ticket','ProductCategory_transport','ProductCategory_tv','ProductCategory_utility_bill','ChannelId_1','ChannelId_2','ChannelId_3','ChannelId_5','ProviderId_1','ProviderId_2','ProviderId_3','ProviderId_4','ProviderId_5','ProviderId_6','Hour_1','Hour_2','Hour_3','Hour_4'], random_state=42)
smotenc= SMOTENC(categorical_features=[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28])
enn_model = EditedNearestNeighbours(sampling_strategy="auto", n_neighbors=3, kind_sel='all',n_jobs=-1)

smotenc_enn = SMOTEENN(sampling_strategy='not minority', smote=smotenc, enn=enn_model, n_jobs=-1)




In [11]:
X_resampled_enn, y_resampled_enn = enn_model.fit_resample(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
print ('Shape of undersampled data : ', y_resampled_enn.value_counts())

Shape of undersampled data :  0    76314
1      157
Name: Fraud, dtype: int64


In [ ]:
X_resampled_smotenc, y_resampled_smotenc = smotenc.fit_resample(X_train, y_train)
print('Number of fraud and not fraud cases in training data: \n', y_resampled_smotenc.value_counts())

MemoryError: Unable to allocate 30.0 GiB for an array with shape (76215, 5, 10552) and data type float64

In [ ]:
#
# create new X_resampled and y_resampled
X_resampled, y_resampled = smotenc_enn.fit_resample(X_train, y_train)

# find the number of fraud and non-fraud cases in the training data
print('Number of fraud and not fraud cases in training data: \n', y_resampled.value_counts())

MemoryError: Unable to allocate 30.0 GiB for an array with shape (76215, 5, 10552) and data type float64

# II. Evaluation
- Confusion matrix
- f1 score
- Prediction on test set