# I. Models
## 1. Undersamlping 
- Random undersampling : EasyEnsembleClassifier using adaboost classifier
- Random undersampling : EasyEnsembleClassifier using gradientboosting classifier



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#import Data
df = pd.read_csv('../../Data/training_clean.csv')

# shape of data
print(df.shape)
df.head()

(95662, 16)


Value  ProviderId_3  ProviderId_5  ProviderId_1  \
0   1000             0             0             0   
1     20             0             0             0   
2    500             0             0             0   
3  21800             0             0             1   
4    644             0             0             0   

   ProductCategory_utility_bill  ProductCategory_financial_services  \
0                             0                                   0   
1                             0                                   1   
2                             0                                   0   
3                             1                                   0   
4                             0                                   1   

   ChannelId_3  Hour_3  Hour_4  ChannelId_1  PricingStrategy_4  \
0            1       0       1            0                  0   
1            0       0       1            0                  0   
2            1       0       1            0                  0   
3            1       0       1            0                  0   
4            0       0       1            0                  0   

   SubscriptionId  ProductCategory_transport  AccountId  PricingStrategy_0  \
0             887                          0       3957                  0   
1            3829                          0       4841                  0   
2             222                          0       4229                  0   
3            2185                          0        648                  0   
4            3829                          0       4841                  0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0

In [2]:
print(df.index)

RangeIndex(start=0, stop=95662, step=1)


In [3]:
# split data into train and test
from sklearn.model_selection import train_test_split
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# find the number of fraud and non-fraud cases in the training data
print('Number of fraud and not fraud cases in training data: \n', y_train.value_counts())
print('Number of fraud and not fraud cases in test data: \n', y_test.value_counts())



Number of fraud and not fraud cases in training data: 
 0    76372
1      157
Name: Fraud, dtype: int64
Number of fraud and not fraud cases in test data: 
 0    19097
1       36
Name: Fraud, dtype: int64


In [5]:
## import EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import classification_report, confusion_matrix, f1_score

# create model
eec = EasyEnsembleClassifier(n_estimators=20, estimator=AdaBoostClassifier() , random_state=42, n_jobs=-1, verbose=0)
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[18813   284]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     19097
           1       0.11      1.00      0.20        36

    accuracy                           0.99     19133
   macro avg       0.56      0.99      0.60     19133
weighted avg       1.00      0.99      0.99     19133



In [6]:
from sklearn.ensemble import GradientBoostingClassifier
# create model
eec = EasyEnsembleClassifier(n_estimators=50, estimator=GradientBoostingClassifier() , random_state=42, n_jobs=-1, verbose=0 )
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[18817   280]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     19097
           1       0.11      1.00      0.20        36

    accuracy                           0.99     19133
   macro avg       0.56      0.99      0.60     19133
weighted avg       1.00      0.99      0.99     19133



In [7]:

# create model
eec_GBC = EasyEnsembleClassifier(n_estimators=40, estimator=GradientBoostingClassifier(), sampling_strategy=0.25 , random_state=42, n_jobs=-1, verbose=0 )
eec_GBC.fit(X_train, y_train)

# predict
y_pred = eec_GBC.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[18986   111]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.99      1.00     19097
           1       0.24      1.00      0.39        36

    accuracy                           0.99     19133
   macro avg       0.62      1.00      0.70     19133
weighted avg       1.00      0.99      1.00     19133



In [8]:
from sklearn.ensemble import RandomForestClassifier
# create model
rfc = EasyEnsembleClassifier(n_estimators=5, estimator=RandomForestClassifier(), sampling_strategy=0.05 , random_state=42, n_jobs=-1, verbose=0 )
rfc.fit(X_train, y_train)

# predict
y_pred = rfc.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19072    25]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.59      1.00      0.74        36

    accuracy                           1.00     19133
   macro avg       0.80      1.00      0.87     19133
weighted avg       1.00      1.00      1.00     19133



In [9]:
from sklearn.ensemble import VotingClassifier

# create model
vc = VotingClassifier(estimators=[('eec', eec), ('rfc_und_over', rfc), ('eec_GBC',eec_GBC)], voting='hard')
vc.fit(X_train, y_train)

# predict
y_pred = vc.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))


Matrix confusion : 
 [[18990   107]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      0.99      1.00     19097
           1       0.25      1.00      0.40        36

    accuracy                           0.99     19133
   macro avg       0.63      1.00      0.70     19133
weighted avg       1.00      0.99      1.00     19133



In [10]:
# create model
eec = EasyEnsembleClassifier(n_estimators=20, estimator=AdaBoostClassifier(), sampling_strategy=0.25 , random_state=42, n_jobs=-1, verbose=0)
eec.fit(X_train, y_train)

# predict
y_pred = eec.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19006    91]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.28      1.00      0.44        36

    accuracy                           1.00     19133
   macro avg       0.64      1.00      0.72     19133
weighted avg       1.00      1.00      1.00     19133



In [11]:
from sklearn.ensemble import RandomForestClassifier
# create model
rfc2 = EasyEnsembleClassifier(n_estimators=2, estimator=RandomForestClassifier(n_estimators=15 ), sampling_strategy=0.01, random_state=42, n_jobs=-1, verbose=0 )
rfc2.fit(X_train, y_train)

# predict
y_pred = rfc2.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19084    13]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.73      1.00      0.85        36

    accuracy                           1.00     19133
   macro avg       0.87      1.00      0.92     19133
weighted avg       1.00      1.00      1.00     19133



## 2. Undersampling and Oversampling
a) Resample
- SMOTEENN : SMOTENC (Categorical and numerical features)+ ENN



...

In [12]:
X_train.shape

(76529, 15)

In [13]:
#import SMOTENC 
from imblearn.over_sampling import SMOTENC
#import ENN
from imblearn.under_sampling import EditedNearestNeighbours

#import SMOTEENN
from imblearn.combine import SMOTEENN

# create model of over and under sampling : SMOTENC and ENN
# categorical features : 'AccountId','SubscriptionId','CustomerId', 'ProductId','PricingStrategy','ProductCategory_airtime','ProductCategory_data_bundles','ProductCategory_financial_services','ProductCategory_movies','ProductCategory_other','ProductCategory_ticket','ProductCategory_transport','ProductCategory_tv','ProductCategory_utility_bill','ChannelId_1','ChannelId_2','ChannelId_3','ChannelId_5','ProviderId_1','ProviderId_2','ProviderId_3','ProviderId_4','ProviderId_5','ProviderId_6','Hour_1','Hour_2','Hour_3','Hour_4'
#smotenc= SMOTENC(categorical_features=['AccountId','SubscriptionId','CustomerId', 'ProductId','PricingStrategy','ProductCategory_airtime','ProductCategory_data_bundles','ProductCategory_financial_services','ProductCategory_movies','ProductCategory_other','ProductCategory_ticket','ProductCategory_transport','ProductCategory_tv','ProductCategory_utility_bill','ChannelId_1','ChannelId_2','ChannelId_3','ChannelId_5','ProviderId_1','ProviderId_2','ProviderId_3','ProviderId_4','ProviderId_5','ProviderId_6','Hour_1','Hour_2','Hour_3','Hour_4'], random_state=42)
#smotenc= SMOTENC(categorical_features=[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28])

# smotenc= SMOTENC(categorical_features=[ 'ProviderId_3', 'ProviderId_5', 'ProviderId_1', 'ProductCategory_utility_bill', 'ProductCategory_financial_services', 
#                                        'ChannelId_3', 'Hour_3', 'Hour_4', 'ChannelId_1', 'PricingStrategy_4', 'SubscriptionId', 'ProductCategory_transport', 
#                                        'AccountId', 'PricingStrategy_0'])


smotenc= SMOTENC(categorical_features=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13, 14])

enn_model = EditedNearestNeighbours(sampling_strategy="auto", n_neighbors=3, kind_sel='all',n_jobs=-1)

smotenc_enn = SMOTEENN(sampling_strategy='not minority', smote=smotenc, enn=enn_model, n_jobs=-1)




In [14]:
#X_resampled_enn, y_resampled_enn = enn_model.fit_resample(X_train, y_train)

In [15]:
# print ('Shape of undersampled data : ', y_resampled_enn.value_counts())

In [16]:
#X_resampled_smotenc, y_resampled_smotenc = smotenc.fit_resample(X_train, y_train)
#print('Number of fraud and not fraud cases in training data: \n', y_resampled_smotenc.value_counts())

In [17]:
#
# create new X_resampled and y_resampled
# X_resampled, y_resampled = smotenc_enn.fit_resample(X_train, y_train)

# # find the number of fraud and non-fraud cases in the training data
# print('Number of fraud and not fraud cases in training data: \n', y_resampled.value_counts())

## 2. Undersampling and Oversampling
a) Resample

- RandomUnderSampler + SMOTEENN 

In [18]:
print (y_train.value_counts())

0    76372
1      157
Name: Fraud, dtype: int64


In [19]:
# import randomUnderSampler
from imblearn.under_sampling import RandomUnderSampler

# create model under sampling 
rus = RandomUnderSampler(sampling_strategy=0.04, random_state=42)

In [20]:
# fit and resample data
X_resampled_rus, y_resampled_rus = rus.fit_resample(X_train, y_train)

In [21]:
print ('value count of undersampled data : ', y_resampled_rus.value_counts())
print ('Shape of undersampled data : ', X_resampled_rus.shape)

value count of undersampled data :  0    3925
1     157
Name: Fraud, dtype: int64
Shape of undersampled data :  (4082, 15)


In [22]:
# Oversampling with SMOTENC fit and resample data
X_resampled_smotenc, y_resampled_smotenc = smotenc.fit_resample(X_resampled_rus, y_resampled_rus)

In [23]:
print ('value count of undersampled data : ', y_resampled_smotenc.value_counts())
print ('Shape of undersampled data : ', X_resampled_smotenc.shape)

value count of undersampled data :  0    3925
1    3925
Name: Fraud, dtype: int64
Shape of undersampled data :  (7850, 15)


## 2. Undersampling and Oversampling
b) Model classifier
- random forest classifier

In [24]:
# create model random forest
rfc_und_over = RandomForestClassifier(n_estimators=30, random_state=42, n_jobs=-1, verbose=0)

# fit and predict
rfc_und_over.fit(X_resampled_smotenc, y_resampled_smotenc)
y_pred = rfc_und_over.predict(X_test)

print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))


Matrix confusion : 
 [[19042    55]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.40      1.00      0.57        36

    accuracy                           1.00     19133
   macro avg       0.70      1.00      0.78     19133
weighted avg       1.00      1.00      1.00     19133



# II. Evaluation

- Prediction on test set

In [25]:
#import Data

df_test = pd.read_csv('../../Data/test_clean.csv')

df_test.head()


Value  ProviderId_3  ProviderId_5  ProviderId_1  \
0   1000             0             1             0   
1   2000             0             1             0   
2     50             0             0             0   
3   3000             0             1             0   
4     60             0             0             0   

   ProductCategory_utility_bill  ProductCategory_financial_services  \
0                             0                                   0   
1                             0                                   1   
2                             0                                   1   
3                             0                                   0   
4                             0                                   1   

   ChannelId_3  Hour_3  Hour_4  ChannelId_1  PricingStrategy_4  \
0            1       0       0            0                  1   
1            1       0       0            0                  0   
2            0       0       0            0                  0   
3            1       0       0            0                  1   
4            0       0       0            0                  0   

   SubscriptionId  ProductCategory_transport  AccountId  PricingStrategy_0  
0            4426                          0       2441                  0  
1            2643                          0       3439                  0  
2            3829                          0       4841                  0  
3            4626                          0       2685                  0  
4            3829                          0       4841                  0

In [26]:
print(df.shape)
print (df.columns)
print(df_test.shape)
print (df_test.columns)

(95662, 16)
Index(['Value', 'ProviderId_3', 'ProviderId_5', 'ProviderId_1',
       'ProductCategory_utility_bill', 'ProductCategory_financial_services',
       'ChannelId_3', 'Hour_3', 'Hour_4', 'ChannelId_1', 'PricingStrategy_4',
       'SubscriptionId', 'ProductCategory_transport', 'AccountId',
       'PricingStrategy_0', 'Fraud'],
      dtype='object')
(45019, 15)
Index(['Value', 'ProviderId_3', 'ProviderId_5', 'ProviderId_1',
       'ProductCategory_utility_bill', 'ProductCategory_financial_services',
       'ChannelId_3', 'Hour_3', 'Hour_4', 'ChannelId_1', 'PricingStrategy_4',
       'SubscriptionId', 'ProductCategory_transport', 'AccountId',
       'PricingStrategy_0'],
      dtype='object')


In [27]:
y_pred_EEC_rfc2=rfc2.predict(df_test)
#print (y_pred.value_counts())

y_pred_rfc=rfc_und_over.predict(df_test)

# show amount of values in y_pred
print (y_pred_rfc)
#print (y_pred.value_counts())
# count the number of values '1' in y_pred
print ("fraud with y_pred_rfc :", np.count_nonzero(y_pred_rfc == 1))
print ("fraud y_pred_EEC_rfc2:", np.count_nonzero(y_pred_EEC_rfc2 == 1))

[0 0 0 ... 0 0 0]
fraud with y_pred_rfc : 260
fraud y_pred_EEC_rfc2: 102


In [30]:
# create submission file
df_test = pd.read_csv('../../Data/test.csv')

sample_submission = pd.DataFrame(df_test['TransactionId'])
sample_submission['FraudResult'] = y_pred_rfc



# submission files

In [31]:
# export submission file
sample_submission.to_csv('../../Data/submission_rfc.csv', index=False)

