# I. Models
## 1. Undersamlping 
- Random undersampling : EasyEnsembleClassifier using GradientBoostingClassifier
- Random undersampling : EasyEnsembleClassifier using adaboost classifier
- Random undersampling : EasyEnsembleClassifier using gradientboosting classifier



In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#import Data
df = pd.read_csv('../../Data/training_clean.csv')

# shape of data
print(df.shape)
df.head()

(95662, 16)


Value  ProviderId_3  ProviderId_5  ProviderId_1  \
0   1000             0             0             0   
1     20             0             0             0   
2    500             0             0             0   
3  21800             0             0             1   
4    644             0             0             0   

   ProductCategory_utility_bill  ProductCategory_financial_services  \
0                             0                                   0   
1                             0                                   1   
2                             0                                   0   
3                             1                                   0   
4                             0                                   1   

   ChannelId_3  Hour_3  Hour_4  ChannelId_1  PricingStrategy_4  \
0            1       0       1            0                  0   
1            0       0       1            0                  0   
2            1       0       1            0                  0   
3            1       0       1            0                  0   
4            0       0       1            0                  0   

   SubscriptionId  ProductCategory_transport  AccountId  PricingStrategy_0  \
0             887                          0       3957                  0   
1            3829                          0       4841                  0   
2             222                          0       4229                  0   
3            2185                          0        648                  0   
4            3829                          0       4841                  0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0

In [56]:
print(df.index)

RangeIndex(start=0, stop=95662, step=1)


In [57]:
# split data into train and test
from sklearn.model_selection import train_test_split
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [58]:
# find the number of fraud and non-fraud cases in the training data
print('Number of fraud and not fraud cases in training data: \n', y_train.value_counts())
print('Number of fraud and not fraud cases in test data: \n', y_test.value_counts())

Number of fraud and not fraud cases in training data: 
 0    76372
1      157
Name: Fraud, dtype: int64
Number of fraud and not fraud cases in test data: 
 0    19097
1       36
Name: Fraud, dtype: int64


In [59]:
## import EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix


In [60]:

# create model EasyEnsembleClassifier using GradientBoostingClassifier
eec_GBC = EasyEnsembleClassifier(n_estimators=5, estimator=GradientBoostingClassifier(n_estimators=10), sampling_strategy=0.01 , random_state=42, n_jobs=-1, verbose=0 )
eec_GBC.fit(X_train, y_train)

# predict
y_pred = eec_GBC.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19095     2]
 [    1    35]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.95      0.97      0.96        36

    accuracy                           1.00     19133
   macro avg       0.97      0.99      0.98     19133
weighted avg       1.00      1.00      1.00     19133



In [61]:
# create model EasyEnsembleClassifier using AdaBoostClassifier
eec_Ada = EasyEnsembleClassifier(n_estimators=10, estimator=AdaBoostClassifier(n_estimators=10), sampling_strategy=0.01 , random_state=42, n_jobs=-1, verbose=0)
eec_Ada.fit(X_train, y_train)

# predict
y_pred = eec_Ada.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19088     9]
 [    1    35]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.80      0.97      0.88        36

    accuracy                           1.00     19133
   macro avg       0.90      0.99      0.94     19133
weighted avg       1.00      1.00      1.00     19133



In [62]:

# create model EasyEnsembleClassifier using RandomForestClassifier
eec_rfc = EasyEnsembleClassifier(n_estimators=2, estimator=RandomForestClassifier(n_estimators=20 ), sampling_strategy=0.01, random_state=42, n_jobs=-1, verbose=0 )
eec_rfc.fit(X_train, y_train)

# predict
y_pred = eec_rfc.predict(X_test)
print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))

Matrix confusion : 
 [[19087    10]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.78      1.00      0.88        36

    accuracy                           1.00     19133
   macro avg       0.89      1.00      0.94     19133
weighted avg       1.00      1.00      1.00     19133



## 2. Undersampling and Oversampling
a) Resample
- SMOTEENN : SMOTENC (Categorical and numerical features)+ ENN



...

In [63]:
X_train.shape

(76529, 15)

In [64]:
#import SMOTENC 
from imblearn.over_sampling import SMOTENC
#import ENN
from imblearn.under_sampling import EditedNearestNeighbours

#import SMOTEENN
from imblearn.combine import SMOTEENN

# create over sampling model: SMOTENC

# smotenc= SMOTENC(categorical_features=[ 'ProviderId_3', 'ProviderId_5', 'ProviderId_1', 'ProductCategory_utility_bill', 'ProductCategory_financial_services', 
#                                        'ChannelId_3', 'Hour_3', 'Hour_4', 'ChannelId_1', 'PricingStrategy_4', 'SubscriptionId', 'ProductCategory_transport', 
#                                        'AccountId', 'PricingStrategy_0'])


smotenc= SMOTENC(categorical_features=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13, 14])


# create under sampling model :  ENN
# enn_model = EditedNearestNeighbours(sampling_strategy="auto", n_neighbors=3, kind_sel='all',n_jobs=-1)

# smotenc_enn = SMOTEENN(sampling_strategy='not minority', smote=smotenc, enn=enn_model, n_jobs=-1)




## 2. Undersampling and Oversampling
a) Resample

- RandomUnderSampler + SMOTEENN 

In [65]:
print (y_train.value_counts())

0    76372
1      157
Name: Fraud, dtype: int64


In [66]:
# import randomUnderSampler
from imblearn.under_sampling import RandomUnderSampler

# create model under sampling 
rus = RandomUnderSampler(sampling_strategy=0.04, random_state=42)

In [67]:
# fit and resample data
X_resampled_rus, y_resampled_rus = rus.fit_resample(X_train, y_train)

In [68]:
print ('value count of undersampled data : ', y_resampled_rus.value_counts())
print ('Shape of undersampled data : ', X_resampled_rus.shape)

value count of undersampled data :  0    3925
1     157
Name: Fraud, dtype: int64
Shape of undersampled data :  (4082, 15)


In [69]:
# Oversampling with SMOTENC fit and resample data
X_resampled_smotenc, y_resampled_smotenc = smotenc.fit_resample(X_resampled_rus, y_resampled_rus)

In [70]:
print ('value count of undersampled data : ', y_resampled_smotenc.value_counts())
print ('Shape of undersampled data : ', X_resampled_smotenc.shape)

value count of undersampled data :  0    3925
1    3925
Name: Fraud, dtype: int64
Shape of undersampled data :  (7850, 15)


## 2. Undersampling and Oversampling
b) Model classifier
- random forest classifier

In [71]:
# create model random forest
rfc_und_over = RandomForestClassifier(n_estimators=30, random_state=42, n_jobs=-1, verbose=0)

# fit and predict
rfc_und_over.fit(X_resampled_smotenc, y_resampled_smotenc)
y_pred = rfc_und_over.predict(X_test)

print('Matrix confusion : \n',confusion_matrix(y_test, y_pred))
print('\n Classification report : \n',classification_report(y_test, y_pred))


Matrix confusion : 
 [[19039    58]
 [    0    36]]

 Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19097
           1       0.38      1.00      0.55        36

    accuracy                           1.00     19133
   macro avg       0.69      1.00      0.78     19133
weighted avg       1.00      1.00      1.00     19133



# II. Evaluation

- Prediction on test set

In [72]:
#import Data

df_test = pd.read_csv('../../Data/test_clean.csv')

df_test.head()


Value  ProviderId_3  ProviderId_5  ProviderId_1  \
0   1000             0             1             0   
1   2000             0             1             0   
2     50             0             0             0   
3   3000             0             1             0   
4     60             0             0             0   

   ProductCategory_utility_bill  ProductCategory_financial_services  \
0                             0                                   0   
1                             0                                   1   
2                             0                                   1   
3                             0                                   0   
4                             0                                   1   

   ChannelId_3  Hour_3  Hour_4  ChannelId_1  PricingStrategy_4  \
0            1       0       0            0                  1   
1            1       0       0            0                  0   
2            0       0       0            0                  0   
3            1       0       0            0                  1   
4            0       0       0            0                  0   

   SubscriptionId  ProductCategory_transport  AccountId  PricingStrategy_0  
0            4426                          0       2441                  0  
1            2643                          0       3439                  0  
2            3829                          0       4841                  0  
3            4626                          0       2685                  0  
4            3829                          0       4841                  0

In [74]:
# Predictions
y_pred_EEC_GBC=eec_GBC.predict(df_test)
y_pred_EEC_Ada=eec_Ada.predict(df_test)
y_pred_EEC_rfc=eec_rfc.predict(df_test)
y_pred_rfc=rfc_und_over.predict(df_test)



# show amount of values in y_pred
print (y_pred_rfc)
#print (y_pred.value_counts())
# count the number of values '1' in y_pred
print ("fraud with y_pred_EEC_GBC :", np.count_nonzero(y_pred_EEC_GBC == 1))
print ("fraud with y_pred_EEC_Ada :", np.count_nonzero(y_pred_EEC_Ada == 1))
print ("fraud with y_pred_EEC_rfc:", np.count_nonzero(y_pred_EEC_rfc == 1))
print ("fraud with y_pred_rfc :", np.count_nonzero(y_pred_rfc == 1))

[0 0 0 ... 0 0 0]
fraud with y_pred_EEC_GBC : 75
fraud with y_pred_EEC_Ada : 84
fraud with y_pred_EEC_rfc: 99
fraud with y_pred_rfc : 255


In [75]:
# create submission file
df_test = pd.read_csv('../../Data/test.csv')

sample_submission_EEC_GBC = pd.DataFrame(df_test['TransactionId'])
sample_submission_EEC_GBC['FraudResult'] = y_pred_EEC_GBC

sample_submission_EEC_Ada = pd.DataFrame(df_test['TransactionId'])
sample_submission_EEC_Ada['FraudResult'] = y_pred_EEC_Ada

sample_submission_EEC_rfc = pd.DataFrame(df_test['TransactionId'])
sample_submission_EEC_rfc['FraudResult'] = y_pred_EEC_rfc

sample_submission_rfc = pd.DataFrame(df_test['TransactionId'])
sample_submission_rfc['FraudResult'] = y_pred_rfc


# submission files

In [76]:
# export submission file
sample_submission_EEC_GBC.to_csv('../../Data/submission_EEC_GBC.csv', index=False)
sample_submission_EEC_Ada.to_csv('../../Data/submission_EEC_Ada.csv', index=False)
sample_submission_EEC_rfc.to_csv('../../Data/submission_EEC_rfc.csv', index=False)
sample_submission_rfc.to_csv('../../Data/submission_rfc.csv', index=False)